### ISSUE TITLE
Implement draft getNumbers

### ISSUE THREAD

**Issue by FishCanCry** [FishCanCry/myalomatika-backend#8]

**Comment by JohnHeit** [comment]
End Point getNumbers was implemented.
Example: http://localhost:8080/getNumbers?level=1&digit=1&count=10&combo=true

return Array of JsonObjects
Example:
["{\"Number\":\"+2\",\"Color\":\"#ff7f00\"}","{\"Number\":\"-1\",\"Color\":\"#a000b5\"}","{\"Number\":\"-1\",\"Color\":\"#0caa00\"}","{\"Number\":\"+3\",\"Color\":\"#a000b5\"}","{\"Number\":\"-1\",\"Color\":\"#ff7f00\"}","{\"Number\":\"+2\",\"Color\":\"#00a4ad\"}","{\"Number\":\"-3\",\"Color\":\"#ff7f00\"}","{\"Number\":\"-1\",\"Color\":\"#3600af\"}","{\"Number\":\"+2\",\"Color\":\"#a000b5\"}","{\"Number\":\"-2\",\"Color\":\"#00a4ad\"}"]
